currencies:
  - GBP-EUR  # British Pound to Euro
  - EUR-BRL  # Euro to Brazilian Real
  - USD-EUR  # US Dollar to Euro
  - BTC-USD  # Bitcoin to US Dollar
  - CNY-USD  # Chinese Yuan to US Dollar
  - USD-JPY  # US Dollar to Japanese Yen
  - EUR-USD  # Euro to US Dollar
  - ETH-USD  # Ethereum to US Dollar
  - GBP-USD  # British Pound to US Dollar
