server:
  port: 7575
  timeout_seconds: 10
  update_interval_seconds: 21600
  retries: 3
  retry_backoff_seconds: 1
  expose_default_metrics: false
  log_level: INFO

pairs:
  - BTC-USD
  - EUR-BRL
  - USD-BRL
  - GBP-EUR
  - EUR-USD
  - CNY-USD
